Ping_Pong::Game1
GraphicsDeviceManager Ping_Pong.Game1.graphics
SpriteBatch Ping_Pong.Game1.spriteBatch
Texture2D Ping_Pong.Game1.spaceBG
Texture2D Ping_Pong.Game1.earthBall
Referenced by Ping_Pong.Game1.LoadGameGraphics.
Texture2D Ping_Pong.Game1.spacePaddle
Referenced by Ping_Pong.Game1.LoadGameGraphics.
SpriteFont Ping_Pong.Game1.name
Random Ping_Pong.Game1.random
bool Ping_Pong.Game1._isPaused
SoundEffect Ping_Pong.Game1.ballBounce
Song Ping_Pong.Game1.spaceSong
int Ping_Pong.Game1.m_Score1
int Ping_Pong.Game1.m_Score2
Texture2D Ping_Pong.Game1.m_textureNumbers
Rectangle [] Ping_Pong.Game1.m_ScoreRect
Ball Ping_Pong.Game1.m_ball
Paddle Ping_Pong.Game1.m_paddle1
Paddle Ping_Pong.Game1.m_paddle2
const int Ping_Pong.Game1.SCREEN_WIDTH
Referenced by Ping_Pong.Game1.InitScreen.
const int Ping_Pong.Game1.SCREEN_HEIGHT
Referenced by Ping_Pong.Game1.InitScreen.
const float Ping_Pong.Game1.PADDLE_STRIDE
Referenced by Ping_Pong.Game1.MovePaddles.
Ping_Pong.Game1.Game1()
void Ping_Pong.Game1.InitScreen()
References Ping_Pong.Game1.SCREEN_HEIGHT, Ping_Pong.Game1.SCREEN_WIDTH.
Referenced by Ping_Pong.Game1.Initialize.
void Ping_Pong.Game1.InitGameObjects()
References Ping_Pong.GameObject.Width, Ping_Pong.GameObject.Height, Ping_Pong.Game1.ResetGame.
Referenced by Ping_Pong.Game1.Initialize.
void Ping_Pong.Game1.ResetGame()
initial play state. called when the game is first run, and when a score of 100 has been reached.
References Ping_Pong.GameObject.X, Ping_Pong.GameObject.Width, Ping_Pong.GameObject.Y, Ping_Pong.GameObject.Height, Ping_Pong.Ball.DX, Ping_Pong.Ball.DY.
Referenced by Ping_Pong.Game1.InitGameObjects, Ping_Pong.Game1.Update, Ping_Pong.Game1.MoveBall.
void Ping_Pong.Game1.DrawScore(float x, float y, int score)
Referenced by Ping_Pong.Game1.Render.
void Ping_Pong.Game1.Render()
References Ping_Pong.Game1.DrawScore, Ping_Pong.GameObject.Visual, Ping_Pong.GameObject.Rect.
Referenced by Ping_Pong.Game1.Draw.
override void Ping_Pong.Game1.Initialize()
Allows the game to perform any initialization it needs to before starting to run. This is where it can query for any required services and load any non-graphic related content. Calling base.Initialize will enumerate through any components and initialize them as well.
References Ping_Pong.Game1.InitScreen, Ping_Pong.Game1.InitGameObjects.
override void Ping_Pong.Game1.LoadContent()
LoadContent is called once per game, and is where all 2D textures, SpriteFonts, Songs, and SoundEffects are loaded. Load cool space graphics with circular earth ball, space ship paddles, future score font, name font, and starry background.
References Ping_Pong.Game1.LoadGameGraphics.
void Ping_Pong.Game1.LoadGameGraphics()
Loads content related to graphical elements
References Ping_Pong.GameObject.Visual, Ping_Pong.Game1.earthBall, Ping_Pong.Game1.spacePaddle.
Referenced by Ping_Pong.Game1.LoadContent.
override void Ping_Pong.Game1.UnloadContent()
UnloadContent will be called once per game and is the place to unload all content.
override void Ping_Pong.Game1.Update(GameTime gameTime)
Allows the game to run logic such as updating the world, checking for collisions, gathering and processing keyboard input, and playing audio.
gameTime Provides a snapshot of timing values.
References Ping_Pong.Game1.ResetGame, Ping_Pong.Game1.MoveBall, Ping_Pong.Game1.MovePaddles.
override void Ping_Pong.Game1.Draw(GameTime gameTime)
This is called when the game should draw itself.
gameTime Provides a snapshot of timing values.
References Ping_Pong.Game1.Render.
void Ping_Pong.Game1.MoveBall()
References Ping_Pong.GameObject.X, Ping_Pong.Ball.DX, Ping_Pong.GameObject.Y, Ping_Pong.Ball.DY, Ping_Pong.GameObject.Height, Ping_Pong.GameObject.Width, Ping_Pong.Game1.ResetGame, Ping_Pong.Game1.CollisionOccurred.
Referenced by Ping_Pong.Game1.Update.
bool Ping_Pong.Game1.CollisionOccurred()
check for a collision between the ball and paddles
References Ping_Pong.Ball.DX, Ping_Pong.GameObject.Rect.
Referenced by Ping_Pong.Game1.MoveBall.
void Ping_Pong.Game1.MovePaddles()
References Ping_Pong.GameObject.Height, Ping_Pong.GameObject.Y, Ping_Pong.Game1.PADDLE_STRIDE.
Referenced by Ping_Pong.Game1.Update.